spring:
  application:
    name: ticketing-mundial2026
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticketing}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres123}
  jpa:
    hibernate:
      ddl-auto: none            # el esquema lo gobierna el SQL, no Hibernate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false

security:
  jwt:
    secret: ${JWT_SECRET:c2VjcmV0by1tdXktbGFyZ28tcGFyYS1obWFjLXNoYTI1Ni1kZW1v}
    expiration-ms: 3600000

server:
  port: 8080
